// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZE69cosM30ga_6yStQayFtdrnLByGK0',
    appId: '1:413422330042:web:092810099891d1c8642283',
    messagingSenderId: '413422330042',
    projectId: 'mobilebank-d515f',
    authDomain: 'mobilebank-d515f.firebaseapp.com',
    databaseURL: 'https://mobilebank-d515f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilebank-d515f.appspot.com',
    measurementId: 'G-ZRS7MC6247',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFm7jmbnj15UYbJS8WOmy6uuLY5FkcPk',
    appId: '1:413422330042:android:bf50eb4e328f367d642283',
    messagingSenderId: '413422330042',
    projectId: 'mobilebank-d515f',
    databaseURL: 'https://mobilebank-d515f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilebank-d515f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_noTZ1fTTN6_CoZJOqIF16AphhpAyyg',
    appId: '1:413422330042:ios:b54394df60a9a7b8642283',
    messagingSenderId: '413422330042',
    projectId: 'mobilebank-d515f',
    databaseURL: 'https://mobilebank-d515f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilebank-d515f.appspot.com',
    iosClientId: '413422330042-qh0jqrtgkjq6ukvntasvirkg2fslsptc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_noTZ1fTTN6_CoZJOqIF16AphhpAyyg',
    appId: '1:413422330042:ios:b54394df60a9a7b8642283',
    messagingSenderId: '413422330042',
    projectId: 'mobilebank-d515f',
    databaseURL: 'https://mobilebank-d515f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilebank-d515f.appspot.com',
    iosClientId: '413422330042-qh0jqrtgkjq6ukvntasvirkg2fslsptc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankapp',
  );
}
